import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import "./globals.css";

import { Box } from "@mui/material";
import styles from "./layout.module.scss";
import { QueryProvider } from "@/providers/queryClientProvider";
import { theme } from "@/themes/theme";
const inter = Inter({ subsets: ["latin"] });
type Metadata = any;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  UserIsLogin: boolean;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body className={inter.className}>
          <QueryProvider>
            <ThemeProvider theme={theme}>
              <ToastContainer
                theme="colored"
                position="top-center"
                autoClose={1000}
              />

              <Box className={styles.Container}>
                <main>{children}</main>
              </Box>
            </ThemeProvider>
          </QueryProvider>
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
